// megafunction wizard: %Altera PLL v17.0%
// GENERATION: XML
// pll.v

// Generated using ACDS version 17.0 595

`timescale 1 ps / 1 ps
module pll (
		input  wire        refclk,   //  refclk.clk
		input  wire        rst,      //   reset.reset
		output wire        outclk_0, // outclk0.clk
		output wire        outclk_1, // outclk1.clk
		output wire        locked,   //  locked.export
		input  wire [63:0] reconfig_to_pll,   // reconfig_to_pll.reconfig_to_pll
		output wire [63:0] reconfig_from_pll  // reconfig_from_pll.reconfig_from_pll
	);

	pll_0002 pll_inst (
		.refclk           (refclk),           //  refclk.clk
		.rst              (rst),              //   reset.reset
		.outclk_0         (outclk_0),         // outclk0.clk
		.outclk_1         (outclk_1),         // outclk1.clk
		.locked           (locked),           //  locked.export
		.reconfig_to_pll  (reconfig_to_pll),  // reconfig_to_pll.reconfig_to_pll
		.reconfig_from_pll(reconfig_from_pll) // reconfig_from_pll.reconfig_from_pll
	);

endmodule
